version: '3'
services:

  # The Application
  app:
    build:
      context: ./app
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./sample-laravel:/var/www/
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - frontend
  # The Web Server
  web:
    build:
      context: ./web
      dockerfile: web.dockerfile
    working_dir: /var/www
    ports:
      - 8080:80
    networks:
      - frontend

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
    networks:
      - frontend
volumes:
  dbdata:
networks:
  frontend:
